version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mongo:4.2
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - porfolio:/data/db

volumes:
  porfolio: